#if !canImport(ObjectiveC)
import XCTest

extension ReteEngineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReteEngineTests = [
        ("testActionPatternSubstitution", testActionPatternSubstitution),
        ("testDuplicate", testDuplicate),
        ("testMultiProductions", testMultiProductions),
        ("testNetwork", testNetwork),
        ("testProductionItems", testProductionItems),
        ("testRuleAction", testRuleAction),
        ("testRuleParser", testRuleParser),
        ("testTokenBinding", testTokenBinding),
        ("testWMEParser", testWMEParser),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReteEngineTests.__allTests__ReteEngineTests),
    ]
}
#endif
